### ISSUE TITLE
"Using static [class];" colored different from other using statements

### ISSUE THREAD

**Issue by SirIntruder** [dotnet/csharp-tmLanguage#122]
![2018-06-04_21-36-24](https://user-images.githubusercontent.com/5102661/40937636-8b0fd3fa-683f-11e8-9e94-d4c22d97c045.png)

I assume this should be white as in other using statements?

**Comment by DustinCampbell** [comment]
No -- this is intentional. `System.Random` is colorized with the type colorization rules, while `System` and `System.Collections.Generic` are not because they can only be namespaces. When we eventually have the ability to provide semantic highlighting to VS Code, we'll be able to identify namespaces and types accurately and colorize them appropriately. However, with regular expressions, this is the best we can do today.
