### ISSUE TITLE
C# 9 Top-Level Statements Syntax Coloring Bugs

### ISSUE THREAD

**Issue by sandyarmstrong** [dotnet/csharp-tmLanguage#203]
Copying from https://github.com/microsoft/vscode/issues/121770...

VS Code Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

0. Ensure C# extension's semantic highlighting is disabled.
1. Write a program using [C# 9 top-level statements](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#top-level-statements).
2. Put `else` clause's statement on same line as the `else`.

Both the `else` and the statement will be colored incorrectly. In this example, you can see `else`, `Console`, and the string are all wrong. Put them inside the context of a method and everything colors correctly again.

My 10 year old noticed this while he was learning a little C# this weekend. It made him think his code was wrong.

![image](https://user-images.githubusercontent.com/155076/115458133-317ab580-a1da-11eb-995b-ead715e46694.png)

https://microsoft.github.io/monaco-editor/index.html does not seem to have the same bug, if that's helpful. It's also not present here on GitHub.

```csharp
using System;

// Bug only seems to occur when using C# 9 top-level statements
// https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#top-level-statements
if (true) {
    Console.WriteLine("normal syntax coloring");
}
else Console.WriteLine("buggy syntax coloring");

if (true) Console.WriteLine("normal syntax coloring");
else Console.WriteLine ("buggy syntax coloring");

// It looks correct if it's wrapped in a method
static void Foo()
{
    if (true) {
        Console.WriteLine("normal syntax coloring");
    }
    else Console.WriteLine("buggy syntax coloring");

    if (true) Console.WriteLine("normal syntax coloring");
    else Console.WriteLine ("buggy syntax coloring");
}
```

Another example:

![image](https://user-images.githubusercontent.com/155076/115458864-2d02cc80-a1db-11eb-874b-95ad864ae7b9.png)

Every word on the `else if` line is colored incorrectly.

**Comment by am11** [comment]
GitHub Linguist repo contains syntax highlighting on GitHub (source code, code snippets in comments etc.). For C# language, GitHub Linguist also uses grammar file directly from this repository (without any modifications). It uses this repo as a git submodule: https://github.com/github/linguist/blob/02f3f0e892904489066ebdb0dcc86192a745e3cb/.gitmodules#L359-L361

We can use GitHub Linguist's lightshow app to validate any grammar file, e.g. for the one produced by this repo: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https://github.com/dotnet/csharp-tmLanguage/blob/main/src/csharp.tmLanguage.yml&grammar_text=&code_source=from-text. Your example code in github-lightshow is highlighted perfectly fine with latest `main` branch of this repo, as we can also see in your GitHub comment.

VSCode OTOH, has a) copy of grammar from this file (rather than submodule for better tracking of which commit it's pointing to), and b) modified grammar than the one produced from this repo. Both a and b are anti patterns IMO and cause such dissimilar behaviors between VSCode and other consumers of this repository.

**Comment by badsyntax** [comment]
Can we get a status update on this issue?

**Comment by tbolon** [comment]
I has exactly the same problem submitted on vscode: https://github.com/OmniSharp/omnisharp-vscode/issues/5472

Basically, top-level statements are not supported.

**Comment by danmoseley** [comment]
@DustinCampbell is this repo actively maintained? It seems this is affecting as well as VS Code also Github C# colorization.

cc @EgorBo

**Comment by DustinCampbell** [comment]
> @DustinCampbell is this repo actively maintained? It seems this is affecting as well as VS Code also Github C# colorization.

Ownership of this repo has fallen into limbo lately. @JoeRobich used to be the active maintainer but has moved onto other things. Looping in @arkalyanms, who is probably the right person to ensure this is updated, since this grammar is used for syntax highlighting in VS Code, VS (when C# isn't installed), and GitHub.

**Comment by danmoseley** [comment]
>  it's just a matter of raising issue to that team to do the same for syntax highlighting.

I don't know how to raise such a ticket, but perhaps someone else does (assuming you're right it's better). not my area.
